# Generated by Django 3.0.8 on 2020-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200719_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_thumbnail',
            field=models.ImageField(default=0, upload_to='faces_pics'),
            preserve_default=False,
        ),
    ]
