# Generated by Django 3.0.8 on 2020-07-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_person_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_last_seen',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_thumbnail',
        ),
    ]
