# Generated by Django 3.0.8 on 2020-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200721_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='person_last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='faces_pics'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
