# Generated by Django 3.0.8 on 2020-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person_person_prediction_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_last_seen',
            field=models.DateTimeField(null=True, verbose_name='date_of_emotion'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='faces_pics/'),
        ),
    ]
