# Generated by Django 3.0.8 on 2020-07-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_overallstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallstats',
            old_name='last_avg_emotion',
            new_name='avg_overall_emotion',
        ),
    ]
