# Generated by Django 3.0.8 on 2020-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200731_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallstats',
            name='avg_overall_plot',
            field=models.ImageField(blank=True, null=True, upload_to='faces_pics/'),
        ),
    ]
