# Generated by Django 3.0.8 on 2020-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_overallstats_avg_overall_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotStats',
            fields=[
                ('plot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='faces_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='OverallStats',
        ),
    ]
